version: '3'
services:
  week4:
    image: adityan28/week4:latest
    ports:
      - "3010:3000"
    restart: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthcheck"]